/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTablesIndexRouteImport } from './routes/_auth/tables/index'
import { Route as AuthStaffIndexRouteImport } from './routes/_auth/staff/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthMenuIndexRouteImport } from './routes/_auth/menu/index'
import { Route as AuthKitchenIndexRouteImport } from './routes/_auth/kitchen/index'
import { Route as AuthBranchesIndexRouteImport } from './routes/_auth/branches/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTablesIndexRoute = AuthTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStaffIndexRoute = AuthStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenuIndexRoute = AuthMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKitchenIndexRoute = AuthKitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBranchesIndexRoute = AuthBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/branches/': typeof AuthBranchesIndexRoute
  '/kitchen/': typeof AuthKitchenIndexRoute
  '/menu/': typeof AuthMenuIndexRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/staff/': typeof AuthStaffIndexRoute
  '/tables/': typeof AuthTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/branches': typeof AuthBranchesIndexRoute
  '/kitchen': typeof AuthKitchenIndexRoute
  '/menu': typeof AuthMenuIndexRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/staff': typeof AuthStaffIndexRoute
  '/tables': typeof AuthTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/branches/': typeof AuthBranchesIndexRoute
  '/_auth/kitchen/': typeof AuthKitchenIndexRoute
  '/_auth/menu/': typeof AuthMenuIndexRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/staff/': typeof AuthStaffIndexRoute
  '/_auth/tables/': typeof AuthTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/branches/'
    | '/kitchen/'
    | '/menu/'
    | '/orders/'
    | '/staff/'
    | '/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/branches'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/staff'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/branches/'
    | '/_auth/kitchen/'
    | '/_auth/menu/'
    | '/_auth/orders/'
    | '/_auth/staff/'
    | '/_auth/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tables/': {
      id: '/_auth/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof AuthTablesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/staff/': {
      id: '/_auth/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthStaffIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menu/': {
      id: '/_auth/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AuthMenuIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kitchen/': {
      id: '/_auth/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof AuthKitchenIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/branches/': {
      id: '/_auth/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthBranchesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthBranchesIndexRoute: typeof AuthBranchesIndexRoute
  AuthKitchenIndexRoute: typeof AuthKitchenIndexRoute
  AuthMenuIndexRoute: typeof AuthMenuIndexRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthStaffIndexRoute: typeof AuthStaffIndexRoute
  AuthTablesIndexRoute: typeof AuthTablesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthBranchesIndexRoute: AuthBranchesIndexRoute,
  AuthKitchenIndexRoute: AuthKitchenIndexRoute,
  AuthMenuIndexRoute: AuthMenuIndexRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthStaffIndexRoute: AuthStaffIndexRoute,
  AuthTablesIndexRoute: AuthTablesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
