/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WaiterRouteImport } from './routes/_waiter'
import { Route as KitchenRouteImport } from './routes/_kitchen'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaiterWaiterRouteImport } from './routes/_waiter/waiter'
import { Route as KitchenKitchenRouteImport } from './routes/_kitchen/kitchen'
import { Route as CustomerOrdersRouteImport } from './routes/_customer/orders'
import { Route as CustomerMenuRouteImport } from './routes/_customer/menu'
import { Route as CustomerCartRouteImport } from './routes/_customer/cart'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminReservationsRouteImport } from './routes/_admin/reservations'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminTablesIndexRouteImport } from './routes/_admin/tables/index'
import { Route as AdminMenuIndexRouteImport } from './routes/_admin/menu/index'
import { Route as CustomerTableTableIdRouteImport } from './routes/_customer/table.$tableId'
import { Route as AdminTablesClassesRouteImport } from './routes/_admin/tables/classes'
import { Route as AdminMenuItemIdRouteImport } from './routes/_admin/menu/$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterRoute = WaiterRouteImport.update({
  id: '/_waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/_kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterWaiterRoute = WaiterWaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => WaiterRoute,
} as any)
const KitchenKitchenRoute = KitchenKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => KitchenRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMenuRoute = CustomerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesIndexRoute = AdminTablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuIndexRoute = AdminMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerTableTableIdRoute = CustomerTableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminTablesClassesRoute = AdminTablesClassesRouteImport.update({
  id: '/tables/classes',
  path: '/tables/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuItemIdRoute = AdminMenuItemIdRouteImport.update({
  id: '/menu/$itemId',
  path: '/menu/$itemId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/reservations': typeof AdminReservationsRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/cart': typeof CustomerCartRoute
  '/menu': typeof CustomerMenuRoute
  '/orders': typeof CustomerOrdersRoute
  '/kitchen': typeof KitchenKitchenRoute
  '/waiter': typeof WaiterWaiterRoute
  '/menu/$itemId': typeof AdminMenuItemIdRoute
  '/tables/classes': typeof AdminTablesClassesRoute
  '/table/$tableId': typeof CustomerTableTableIdRoute
  '/menu/': typeof AdminMenuIndexRoute
  '/tables/': typeof AdminTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/reservations': typeof AdminReservationsRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/cart': typeof CustomerCartRoute
  '/menu': typeof AdminMenuIndexRoute
  '/orders': typeof CustomerOrdersRoute
  '/kitchen': typeof KitchenKitchenRoute
  '/waiter': typeof WaiterWaiterRoute
  '/menu/$itemId': typeof AdminMenuItemIdRoute
  '/tables/classes': typeof AdminTablesClassesRoute
  '/table/$tableId': typeof CustomerTableTableIdRoute
  '/tables': typeof AdminTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_customer': typeof CustomerRouteWithChildren
  '/_kitchen': typeof KitchenRouteWithChildren
  '/_waiter': typeof WaiterRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/reservations': typeof AdminReservationsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/staff': typeof AdminStaffRoute
  '/_customer/cart': typeof CustomerCartRoute
  '/_customer/menu': typeof CustomerMenuRoute
  '/_customer/orders': typeof CustomerOrdersRoute
  '/_kitchen/kitchen': typeof KitchenKitchenRoute
  '/_waiter/waiter': typeof WaiterWaiterRoute
  '/_admin/menu/$itemId': typeof AdminMenuItemIdRoute
  '/_admin/tables/classes': typeof AdminTablesClassesRoute
  '/_customer/table/$tableId': typeof CustomerTableTableIdRoute
  '/_admin/menu/': typeof AdminMenuIndexRoute
  '/_admin/tables/': typeof AdminTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/reservations'
    | '/settings'
    | '/staff'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/kitchen'
    | '/waiter'
    | '/menu/$itemId'
    | '/tables/classes'
    | '/table/$tableId'
    | '/menu/'
    | '/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/reservations'
    | '/settings'
    | '/staff'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/kitchen'
    | '/waiter'
    | '/menu/$itemId'
    | '/tables/classes'
    | '/table/$tableId'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_customer'
    | '/_kitchen'
    | '/_waiter'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/reservations'
    | '/_admin/settings'
    | '/_admin/staff'
    | '/_customer/cart'
    | '/_customer/menu'
    | '/_customer/orders'
    | '/_kitchen/kitchen'
    | '/_waiter/waiter'
    | '/_admin/menu/$itemId'
    | '/_admin/tables/classes'
    | '/_customer/table/$tableId'
    | '/_admin/menu/'
    | '/_admin/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  KitchenRoute: typeof KitchenRouteWithChildren
  WaiterRoute: typeof WaiterRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_waiter': {
      id: '/_waiter'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kitchen': {
      id: '/_kitchen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_waiter/waiter': {
      id: '/_waiter/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterWaiterRouteImport
      parentRoute: typeof WaiterRoute
    }
    '/_kitchen/kitchen': {
      id: '/_kitchen/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenKitchenRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_customer/orders': {
      id: '/_customer/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/menu': {
      id: '/_customer/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof CustomerMenuRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/cart': {
      id: '/_customer/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reservations': {
      id: '/_admin/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tables/': {
      id: '/_admin/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof AdminTablesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/menu/': {
      id: '/_admin/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AdminMenuIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/table/$tableId': {
      id: '/_customer/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof CustomerTableTableIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_admin/tables/classes': {
      id: '/_admin/tables/classes'
      path: '/tables/classes'
      fullPath: '/tables/classes'
      preLoaderRoute: typeof AdminTablesClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/menu/$itemId': {
      id: '/_admin/menu/$itemId'
      path: '/menu/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof AdminMenuItemIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminMenuItemIdRoute: typeof AdminMenuItemIdRoute
  AdminTablesClassesRoute: typeof AdminTablesClassesRoute
  AdminMenuIndexRoute: typeof AdminMenuIndexRoute
  AdminTablesIndexRoute: typeof AdminTablesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminMenuItemIdRoute: AdminMenuItemIdRoute,
  AdminTablesClassesRoute: AdminTablesClassesRoute,
  AdminMenuIndexRoute: AdminMenuIndexRoute,
  AdminTablesIndexRoute: AdminTablesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerMenuRoute: typeof CustomerMenuRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerTableTableIdRoute: typeof CustomerTableTableIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerMenuRoute: CustomerMenuRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerTableTableIdRoute: CustomerTableTableIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface KitchenRouteChildren {
  KitchenKitchenRoute: typeof KitchenKitchenRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenKitchenRoute: KitchenKitchenRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

interface WaiterRouteChildren {
  WaiterWaiterRoute: typeof WaiterWaiterRoute
}

const WaiterRouteChildren: WaiterRouteChildren = {
  WaiterWaiterRoute: WaiterWaiterRoute,
}

const WaiterRouteWithChildren =
  WaiterRoute._addFileChildren(WaiterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  KitchenRoute: KitchenRouteWithChildren,
  WaiterRoute: WaiterRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
